/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../src/components/hero-detail/hero-detail.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../src/services/hero.service';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/common/src/location/location';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './hero-detail.component.css.shim';
import * as import14 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import18 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import19 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/ng_model';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_HeroDetailComponent {
  context:import0.HeroDetailComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.HeroDetailComponent(p0,p1,p2);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_HeroDetailComponent_Host:import2.RenderComponentType = (null as any);
class _View_HeroDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HeroDetailComponent_0_4:Wrapper_HeroDetailComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HeroDetailComponent_Host0,renderType_HeroDetailComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'my-hero-detail',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeroDetailComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroDetailComponent_0_4 = new Wrapper_HeroDetailComponent(this.parentInjector.get(import8.HeroService),this.parentInjector.get(import9.ActivatedRoute),this.parentInjector.get(import10.Location));
    this._appEl_0.initComponent(this._HeroDetailComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HeroDetailComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeroDetailComponent) && (0 === requestNodeIndex))) { return this._HeroDetailComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeroDetailComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._HeroDetailComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroDetailComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HeroDetailComponent_Host === (null as any))) { (renderType_HeroDetailComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HeroDetailComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroDetailComponentNgFactory:import12.ComponentFactory<import0.HeroDetailComponent> = new import12.ComponentFactory<import0.HeroDetailComponent>('my-hero-detail',viewFactory_HeroDetailComponent_Host0,import0.HeroDetailComponent);
const styles_HeroDetailComponent:any[] = [import13.styles];
var renderType_HeroDetailComponent:import2.RenderComponentType = (null as any);
class _View_HeroDetailComponent0 extends import1.AppView<import0.HeroDetailComponent> {
  _anchor_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import14.Wrapper_NgIf;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HeroDetailComponent0,renderType_HeroDetailComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import15.TemplateRef_(this._appEl_0,viewFactory_HeroDetailComponent1);
    this._NgIf_0_6 = new import14.Wrapper_NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init(([] as any[]),[
      this._anchor_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import16.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.hero;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.detectChangesInInputProps(this,this._anchor_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_HeroDetailComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HeroDetailComponent> {
  if ((renderType_HeroDetailComponent === (null as any))) { (renderType_HeroDetailComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_HeroDetailComponent,{})); }
  return new _View_HeroDetailComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeroDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_16_4:any[];
  _NgModel_16_5:import18.Wrapper_NgModel;
  _NgControl_16_6:any;
  _NgControlStatus_16_7:import19.Wrapper_NgControlStatus;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HeroDetailComponent1,renderType_HeroDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'label',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'id: ',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_0,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_11,'label',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'name: ',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_11,'input',new import4.InlineArray2(2,'placeholder','name'),(null as any));
    this._DefaultValueAccessor_16_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_16));
    this._NG_VALUE_ACCESSOR_16_4 = [this._DefaultValueAccessor_16_3.context];
    this._NgModel_16_5 = new import18.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_16_4);
    this._NgControl_16_6 = this._NgModel_16_5.context;
    this._NgControlStatus_16_7 = new import19.Wrapper_NgControlStatus(this._NgControl_16_6);
    this._text_17 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_0,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Back',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_0,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Save',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_16,'input',this.eventHandler(this._handle_input_16_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_16,'blur',this.eventHandler(this._handle_blur_16_2.bind(this)));
    const subscription_0:any = this._NgModel_16_5.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_22,'click',this.eventHandler(this._handle_click_22_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_4; }
    if (((token === import23.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_5.context; }
    if (((token === import24.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_6; }
    if (((token === import25.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_16_3.detectChangesInInputProps(this,this._el_16,throwOnChange);
    const currVal_16_1_0:any = this.parent.context.hero.name;
    this._NgModel_16_5.check_model(currVal_16_1_0,throwOnChange,false);
    this._NgModel_16_5.detectChangesInInputProps(this,this._el_16,throwOnChange);
    this._NgControlStatus_16_7.detectChangesInInputProps(this,this._el_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_30:any = import4.interpolate(1,'',this.parent.context.hero.name,' details!');
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setText(this._text_3,currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = import4.interpolate(1,'',this.parent.context.hero.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_9,currVal_31);
      this._expr_31 = currVal_31;
    }
    this._DefaultValueAccessor_16_3.detectChangesInHostProps(this,this._el_16,throwOnChange);
    this._NgModel_16_5.detectChangesInHostProps(this,this._el_16,throwOnChange);
    this._NgControlStatus_16_7.detectChangesInHostProps(this,this._el_16,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_16_5.context.ngOnDestroy();
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_16_0:any = ((<any>(this.parent.context.hero.name = $event)) !== false);
    return (true && pd_16_0);
  }
  private _handle_input_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_16_0:any = ((<any>this._DefaultValueAccessor_16_3.context.onChange($event.target.value)) !== false);
    return (true && pd_16_0);
  }
  private _handle_blur_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_16_0:any = ((<any>this._DefaultValueAccessor_16_3.context.onTouched()) !== false);
    return (true && pd_16_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_19_0:any = ((<any>this.parent.context.goBack()) !== false);
    return (true && pd_19_0);
  }
  private _handle_click_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_22_0:any = ((<any>this.parent.context.save()) !== false);
    return (true && pd_22_0);
  }
}
function viewFactory_HeroDetailComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_HeroDetailComponent1(viewUtils,parentInjector,declarationEl);
}