/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../src/components/hero-search/hero-search.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../../../src/services/hero.service';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './hero-search.component.css.shim';
export class Wrapper_HeroSearchComponent {
  context:import0.HeroSearchComponent;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.HeroSearchComponent(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_HeroSearchComponent_Host:import2.RenderComponentType = (null as any);
class _View_HeroSearchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HeroService_0_4:import4.HeroService;
  _HeroSearchComponent_0_5:Wrapper_HeroSearchComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_HeroSearchComponent_Host0,renderType_HeroSearchComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'hero-search',import5.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeroSearchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroService_0_4 = new import4.HeroService(this.parentInjector.get(import9.Http));
    this._HeroSearchComponent_0_5 = new Wrapper_HeroSearchComponent(this._HeroService_0_4,this.parentInjector.get(import10.Router));
    this._appEl_0.initComponent(this._HeroSearchComponent_0_5.context,([] as any[]),compView_0);
    compView_0.create(this._HeroSearchComponent_0_5.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.HeroService) && (0 === requestNodeIndex))) { return this._HeroService_0_4; }
    if (((token === import0.HeroSearchComponent) && (0 === requestNodeIndex))) { return this._HeroSearchComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeroSearchComponent_0_5.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._HeroSearchComponent_0_5.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroSearchComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HeroSearchComponent_Host === (null as any))) { (renderType_HeroSearchComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HeroSearchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroSearchComponentNgFactory:import12.ComponentFactory<import0.HeroSearchComponent> = new import12.ComponentFactory<import0.HeroSearchComponent>('hero-search',viewFactory_HeroSearchComponent_Host0,import0.HeroSearchComponent);
const styles_HeroSearchComponent:any[] = [import13.styles];
var renderType_HeroSearchComponent:import2.RenderComponentType = (null as any);
class _View_HeroSearchComponent0 extends import1.AppView<import0.HeroSearchComponent> {
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_HeroSearchComponent0,renderType_HeroSearchComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this.init(([] as any[]),([] as any[]),([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_HeroSearchComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HeroSearchComponent> {
  if ((renderType_HeroSearchComponent === (null as any))) { (renderType_HeroSearchComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_HeroSearchComponent,{})); }
  return new _View_HeroSearchComponent0(viewUtils,parentInjector,declarationEl);
}